name: 'Calver Release'
description: 'Automatically create Calver compliant tags or releases based on PR labels'
author: 'Stéphane Bour'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  release_branch:
    description: 'Branch to tag'
    required: true
    default: master
  message:
    description: 'The message of the release'
    required: true
    default: '0'
  draft:
    description: 'Is draft ?'
    required: true
    default: 'false'
  pre:
    description: 'Is pre-release ?'
    required: true
    default: 'false'

outputs:
  tag:
    description: 'The newly created tag'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release_branch }}
    - ${{ inputs.message }}
    - ${{ inputs.draft }}
    - ${{ inputs.pre }}
